name: CI Servicios (Docker)

on:
  push:
    branches: [ "main" ]
    paths:
      - "Sales-System/**"
      - "docker-compose.yml"
      - ".github/workflows/ci-services.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "Sales-System/**"
      - "docker-compose.yml"
      - ".github/workflows/ci-services.yml"

permissions:
  contents: read
  packages: write   # publicar imágenes en GHCR

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service: [ "cliente-service", "producto-service", "usuario-service", "venta-service" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push image
        uses: docker/build-push-action@v5
        with:
          context: Sales-System/${{ matrix.service }}
          file: Sales-System/${{ matrix.service }}/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.service }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ matrix.service }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
